// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wljaklyrlhubgcdnacia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsamFrbHlybGh1YmdjZG5hY2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjY3NjIsImV4cCI6MjA3NDcwMjc2Mn0.bN37ROUWndxWVLOPY_jnC-uR8sUqaUzAt9AUepAz21I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});